### ISSUE TITLE
Missing Frames on Dead Animation

### ISSUE THREAD

**Issue by valentinwinkelmann** [RoboClonk/RenderClonkAddon#2]
![image](https://user-images.githubusercontent.com/4693234/236510160-df983ff6-fcef-45a8-b449-15f0df8e5bfa.png)

There seems to be a bug with the Dead animation, it is always given with a frame length of 8, but there are always 2 frames missing, so the clonk would become invisible when it dies.

This is the ActMap Dead Action:
[Action]
Name=Dead
Length=8
Facet=0,240,16,20

**Comment by RoboClonk** [comment]
Thanks for testing the add-on!

The dead animation was setup this way in the past. If you look inside act map of a the Clonk for example, it uses only 6 frames as well, even though there is empty space in the sprite sheet. It is no longer needed, so you can just reduce the frames of this animation in the add-on by 2.

The plan for the future is an overhaul of the Clonk content files to store correct/usable values. So we won't import wrong values all the time.

Since this is unrelated to the add-on itself, I will close this issue.

**Comment by valentinwinkelmann** [comment]
That's good to know Thankyou, I was confused why always this animation had empty frames.
